### ISSUE TITLE
WebSocketIT randomly failing

### ISSUE THREAD

**Issue by pith** [seedstack/seed#146]
Fix the following tests.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
10:30:43.191 [http-bio-59543-exec-2] ERROR o.a.t.w.pojo.PojoEndpointBase - No error handling configured for [org.seedstack.seed.web.ChatEndpoint] and the following error occurred
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1122) ~[tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1085) ~[tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:186) ~[tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37) ~[tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.seedstack.seed.web.ChatEndpoint.message(ChatEndpoint.java:28) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80) ~[tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:393) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:494) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:289) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:56) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:203) [tomcat-embed-websocket-7.0.57.jar:7.0.57]
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:203) [tomcat-embed-core-7.0.57.jar:7.0.57]
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:92) [tomcat-embed-core-7.0.57.jar:7.0.57]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:609) [tomcat-embed-core-7.0.57.jar:7.0.57]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-embed-core-7.0.57.jar:7.0.57]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-7.0.57.jar:7.0.57]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Running org.seedstack.seed.web.internal.ServerFactoryTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.968 sec <<< FAILURE! - in org.seedstack.seed.web.WebSocketIT
websocket_communication_is_working(org.seedstack.seed.web.WebSocketIT)  Time elapsed: 2.881 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.seedstack.seed.web.WebSocketIT.websocket_communication_is_working(WebSocketIT.java:63)
Results :
Failed tests: 
  WebSocketIT.websocket_communication_is_working:63 null
```

Log from this [travis build](https://travis-ci.org/seedstack/seed/builds/88084051).

**Comment by adrienlauer** [comment]
Duplicated by #178
