### ISSUE TITLE
Tomcat doesn't start if log level DEBUG

### ISSUE THREAD

**Issue by tbouvet** [seedstack/seed#147]
With

```
<root level="DEBUG">
```

tomcat doesn' start. 

```
java.lang.ClassCircularityError: java/util/logging/LogRecord
    at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:200)
    at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:291)
    at java.util.logging.Logger.log(Logger.java:616)
    at java.util.logging.Logger.doLog(Logger.java:641)
    at java.util.logging.Logger.logp(Logger.java:757)
    at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:183)
    at org.apache.juli.logging.DirectJDKLog.debug(DirectJDKLog.java:106)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:369)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:689)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:321)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:455)
```

A solution could be : http://stackoverflow.com/questions/2656565/classcircularityerror-when-running-tomcat-6-from-eclipse

**Comment by adrienlauer** [comment]
We already detected this problem some time ago. It is due to our logback defaults. The level change propagator is required for good performance. 

Maybe we should just force an info level on the tomcat logger. Otherwise I think it would be difficult to fix this problem without compromising performance or ease of use.

**Comment by adrienlauer** [comment]
We detected this problem some time ago. It is due to our logback defaults. The level change propagator is required for good performance. 

Maybe we should just force an info level on the tomcat logger.

Otherwise I think it would be difficult to fix this problem without compromising performance or ease of use. 

But this should´nt prevent us from trying :-)

**Comment by tbouvet** [comment]
Yes I agree to force info level on the tomcat logger.

**Comment by adrienlauer** [comment]
Done in logback-defaults.xml and LogbackLogManager of 3.0.0.
