### ISSUE TITLE
Crash when gathering diagnostic information on WAS8.5

### ISSUE THREAD

**Issue by Nyamiou** [seedstack/seed#80]
Hello,

I got this with an application on the current version of SEED on a WAS8.5 server after that the application throw an uncaught exception :

    [7/22/15 17:39:08:211 CEST] 0000007c SystemOut     O   [2015-07-22 17:39:08,210] ERROR [o.s.seed.core.internal.DiagnosticManagerImpl : 85] - Unable to write diagnostic information
    org.seedstack.seed.core.api.SeedException: (COREUTILS) Method invocation failed
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86) ~[na:1.7.0]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58) ~[na:1.7.0]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542) ~[na:2.6 (12-15-2014)]
        at org.seedstack.seed.core.api.SeedException.wrap(SeedException.java:435) ~[seed-core-support-specs-2.0.0-M3.jar:na]
        at org.seedstack.seed.core.api.SeedException.wrap(SeedException.java:419) ~[seed-core-support-specs-2.0.0-M3.jar:na]
        at org.seedstack.seed.core.utils.SeedReflectionUtils.invokeMethod(SeedReflectionUtils.java:587) ~[seed-core-support-core-2.0.0-M3.jar:na]
        at org.seedstack.seed.web.internal.WebDiagnosticCollector.buildFilterList(WebDiagnosticCollector.java:70) ~[seed-web-support-core-2.0.0-M3.jar:na]
        at org.seedstack.seed.web.internal.WebDiagnosticCollector.collect(WebDiagnosticCollector.java:36) ~[seed-web-support-core-2.0.0-M3.jar:na]
        at org.seedstack.seed.core.internal.DiagnosticManagerImpl.collectAllDiagnostics(DiagnosticManagerImpl.java:110) ~[seed-core-support-core-2.0.0-M3.jar:na]
        at org.seedstack.seed.core.internal.DiagnosticManagerImpl.dumpDiagnosticReport(DiagnosticManagerImpl.java:83) ~[seed-core-support-core-2.0.0-M3.jar:na]
        at org.seedstack.seed.core.internal.CorePlugin$3.uncaughtException(CorePlugin.java:79) [seed-core-support-core-2.0.0-M3.jar:na]
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:845) [na:1.7.0]
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:843) [na:1.7.0]
        at java.lang.Thread.uncaughtException(Thread.java:1384) [na:1.7.0]
    Caused by: java.lang.NoSuchMethodException: com.ibm.ws.webcontainer.filter.FilterConfig.getInitParameters()
        at java.lang.Class.throwNoSuchMethodException(Class.java:446) ~[na:1.7.0]
        at java.lang.Class.getDeclaredMethod(Class.java:879) ~[na:1.7.0]
        at org.seedstack.seed.core.utils.SeedReflectionUtils.invokeMethod(SeedReflectionUtils.java:583) ~[seed-core-support-core-2.0.0-M3.jar:na]
        ... 8 common frames omitted

I think that getInitParameters() is probably in an inherited class of com.ibm.ws.webcontainer.filter.FilterConfig and since SeedReflectionsUtils.invokeMethod(...) doesn't look in super class it fails to find the method.

**Comment by tbouvet** [comment]
Thank you for your report @Nyamiou !
 As you can see the bug was fixed in the latest snapshot, which will be released on 28th of July.
